#!/system/xbin/bash
: '
 ============ Copyright (C) 2010 Jared Rummler (JRummy16) ============
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 =====================================================================
' 

. /system/etc/liberty.cfg

if busybox [ $FREE_MEM_AT_BOOT -eq 1 ]; then

	busybox echo $FOREGROUND_APP_MEM,$VISIBLE_APP_MEM,$PERCEPTIBLE_APP_MEM,$SECONDARY_SERVER_MEM,$HIDDEN_APP_MEM,$EMPTY_APP_MEM > /sys/module/lowmemorykiller/parameters/minfree

	setprop ro.FOREGROUND_APP_MEM $FOREGROUND_APP_MEM
	setprop ro.VISIBLE_APP_MEM $VISIBLE_APP_MEM
	setprop ro.PERCEPTIBLE_APP_MEM $PERCEPTIBLE_APP_MEM
	setprop ro.HEAVY_WEIGHT_APP_MEM $HEAVY_WEIGHT_APP_MEM
	setprop ro.SECONDARY_SERVER_MEM $SECONDARY_SERVER_MEM
	setprop ro.BACKUP_APP_MEM $BACKUP_APP_MEM
	setprop ro.HOME_APP_MEM $HOME_APP_MEM
	setprop ro.HIDDEN_APP_MEM $HIDDEN_APP_MEM
	setprop ro.EMPTY_APP_MEM $EMPTY_APP_MEM

	RAM_FREE=` busybox expr $EMPTY_APP_MEM \* 4 / 1024 `
	log -p i -t boot "Set ${RAM_FREE}mb of RAM free."

fi