#!/system/xbin/bash
: '
 ============ Copyright (C) 2010 Jared Rummler (JRummy16) ============
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 =====================================================================
' 

. /system/etc/liberty.cfg

if busybox [ $REMOVE_CACHE -eq 1 ]; then
	CACHE_DIR=(` busybox find /data/data -type d -iname *cache* -print `);
	for dir in ${CACHE_DIR[*]}; do
		busybox find $dir -type f -delete
	done
	log -p i -t boot "Cleared data cache..."
fi
