add_lunch_combo aokp_maguro-userdebug
add_lunch_combo aokp_mako-userdebug
add_lunch_combo aokp_manta-userdebug
add_lunch_combo aokp_toro-userdebug
add_lunch_combo aokp_toroplus-userdebug
add_lunch_combo aokp_grouper-userdebug
