add_lunch_combo aokp_crespo-userdebug
add_lunch_combo aokp_crespo4g-userdebug
add_lunch_combo aokp_maguro-userdebug
add_lunch_combo aokp_grouper-userdebug
add_lunch_combo aokp_stingray-userdebug
add_lunch_combo aokp_toro-userdebug
add_lunch_combo aokp_toroplus-userdebug
add_lunch_combo aokp_wingray-userdebug
