add_lunch_combo aokp_d2att-userdebug
add_lunch_combo aokp_d2tmo-userdebug
add_lunch_combo aokp_d2usc-userdebug
add_lunch_combo aokp_d2vzw-userdebug
add_lunch_combo aokp_maguro-userdebug
add_lunch_combo aokp_mako-userdebug
add_lunch_combo aokp_manta-userdebug
add_lunch_combo aokp_toro-userdebug
# add_lunch_combo aokp_toroplus-userdebug
add_lunch_combo aokp_grouper-userdebug
