PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/a510.mk \
    $(LOCAL_DIR)/d2att.mk \
    $(LOCAL_DIR)/d2tmo.mk \
    $(LOCAL_DIR)/d2usc.mk \
    $(LOCAL_DIR)/d2vzw.mk \
    $(LOCAL_DIR)/evita.mk \
    $(LOCAL_DIR)/grouper.mk \
    $(LOCAL_DIR)/hayabusa.mk \
    $(LOCAL_DIR)/hercules.mk \
    $(LOCAL_DIR)/i605.mk \
    $(LOCAL_DIR)/i9100.mk \
    $(LOCAL_DIR)/i9100g.mk \
    $(LOCAL_DIR)/i9300.mk \
    $(LOCAL_DIR)/jfltetmo.mk \
    $(LOCAL_DIR)/l900.mk \
    $(LOCAL_DIR)/m7.mk \
    $(LOCAL_DIR)/maguro.mk \
    $(LOCAL_DIR)/mako.mk \
    $(LOCAL_DIR)/manta.mk \
    $(LOCAL_DIR)/maserati.mk \
    $(LOCAL_DIR)/mint.mk \
    $(LOCAL_DIR)/odin.mk \
    $(LOCAL_DIR)/p930.mk \
    $(LOCAL_DIR)/solana.mk \
    $(LOCAL_DIR)/spyder.mk \
    $(LOCAL_DIR)/su640.mk \
    $(LOCAL_DIR)/targa.mk \
    $(LOCAL_DIR)/t0lte.mk \
    $(LOCAL_DIR)/tilapia.mk \
    $(LOCAL_DIR)/toro.mk \
    $(LOCAL_DIR)/toroplus.mk \
    $(LOCAL_DIR)/tsubasa.mk \
    $(LOCAL_DIR)/umtsspyder.mk \
    $(LOCAL_DIR)/vs920.mk \
    $(LOCAL_DIR)/yuga.mk
