PRODUCT_MAKEFILES := \
    $(LOCAL_DIR)/maguro.mk \
    $(LOCAL_DIR)/toro.mk \
    $(LOCAL_DIR)/crespo.mk \
    $(LOCAL_DIR)/crespo4g.mk \
    $(LOCAL_DIR)/picasso.mk \
    $(LOCAL_DIR)/captivatemtd.mk \
    $(LOCAL_DIR)/fascinatemtd.mk \
    $(LOCAL_DIR)/galaxysmtd.mk \
    $(LOCAL_DIR)/inc.mk \
    $(LOCAL_DIR)/otter.mk \
    $(LOCAL_DIR)/p1c.mk \
    $(LOCAL_DIR)/p4.mk \
    $(LOCAL_DIR)/p4vzw.mk \
    $(LOCAL_DIR)/p4wifi.mk \
    $(LOCAL_DIR)/p5wifi.mk \
    $(LOCAL_DIR)/p990.mk \
    $(LOCAL_DIR)/p999.mk \
    $(LOCAL_DIR)/pyramid.mk \
    $(LOCAL_DIR)/stingray.mk \
    $(LOCAL_DIR)/supersonic.mk \
    $(LOCAL_DIR)/tenderloin.mk \
    $(LOCAL_DIR)/tf101.mk \
    $(LOCAL_DIR)/vibrantmtd.mk \
    $(LOCAL_DIR)/vivow.mk \
    $(LOCAL_DIR)/wingray.mk \
