#!/bin/sh

# Exports
dir=$ANDROID_BUILD_TOP
out=$dir/out/target/product
. $dir/vendor/cm/tools/colors

export Changelog=Changelog.txt

if [ -f $Changelog ];
then
	rm -f $Changelog
fi

touch $Changelog
if [ "$MAKE_CHANGELOG" == "true" ];
then
# Print something to build output
echo ${bldppl}"Generating changelog..."${txtrst}

for i in $(seq 20);
do
export After_Date=`date --date="$i days ago" +%m-%d-%Y`
k=$(expr $i - 1)
	export Until_Date=`date --date="$k days ago" +%m-%d-%Y`

	# Line with after --- until was too long for a small ListView
	echo '====================' >> $Changelog;
	echo  "     "$Until_Date       >> $Changelog;
	echo '===================='	>> $Changelog;
	echo >> $Changelog;

	# Cycle through every repo to find commits between 2 dates
	repo forall -pc 'git log --oneline --after=$After_Date --until=$Until_Date' >> $Changelog
	echo >> $Changelog;
done

sed -i 's/project/   */g' $Changelog

rm -f $OUT/$Changelog
rm -f $OUT/system/etc/$Changelog
cp $Changelog $OUT/system/etc/
cp $Changelog $OUT/
rm $Changelog
else
echo ${bldppl}"Using Prebuilt Changelog"${txtrst}
cp vendor/cm/CHANGELOG.mkdn $OUT/system/etc/$Changelog
fi
